name: CI Build

on:
  pull_request:
    branches: [ master ]

jobs:
  testing:
    name: Testing
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bundle Install 
      run: bundle install

    - name: Bundle Update 
      run: bundle update --bundler

    - name: Build and Tests 
      run: bundle exec fastlane run_unit_tests
