name: CI Test Build

on:
  pull_request:
    branches: [ master ]

env:
  PROJECT: runitz.xcodeproj
  SCHEME: runitz

jobs:
  unitTests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Manual Testing"
        run: xcodebuild clean build test -project ${{ env.PROJECT }} -scheme ${{ env.SCHEME }} -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" | xcpretty
        