name: CI Test Build

on:
  pull_request:
    branches: [ master ]

env:
  PROJECT: runitz
  SCHEME: runitz

jobs:
  unitTests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: devbotsxyz/xcode-build@v1

    # - name: Testing 
    #   uses: devbotsxyz/xcode-test@v1

    - name: "Testing"
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: $PROJECT
        scheme: $SCHEME
        destination: platform=macOS
        action: test
